### ISSUE TITLE
Assert traceback is missing

### ISSUE THREAD

**Issue by SeriousBug** [eerimoq/nala#1]
I downloaded the `nala.c` and `nala.h` files into a directory, and then created a file `test.c` with the following contents:

```
#include <time.h>
#include "nala.h"

TEST(time_test)
{
    ASSERT_EQ(time(NULL), 42);
}
```

Building this with `gcc -g test.c nala.c ` and running the resulting file creates this output:

```
  Test:  test::time_test
  Error: 1598369363 is not equal to 42 (0x5f452e53, 0x2a)

  Assert traceback (most recent call first):

FAILED test::time_test (20ms)

Tests: 1 failed, 1 total
Time: 20ms
```

This is using `gcc (Ubuntu 18.04) 7.5.0`.

Note that the traceback is missing. Is the nala python application required for the traceback?

**Comment by eerimoq** [comment]
There are recommended compiler flags in the readme: https://github.com/eerimoq/nala#compiler-flags

```
$ gcc -no-pie -g -O0 test.c nala.c
$ ./a.out 
...
  Test:  test::time_test
  Error: 1598373220 is not equal to 42 (0x5f453d64, 0x2a)

  Assert traceback (most recent call first):
    at /home/erik/workspace/ttt/test.c:6 in time_test()
        ASSERT_EQ(time(NULL), 42);

FAILED test::time_test (41ms)

Tests: 1 failed, 1 total
Time: 41ms
```

**Comment by eerimoq** [comment]
@SeriousBug Does it work for you as well?
