### ISSUE TITLE
Emit line numbers in the assertion macros

### ISSUE THREAD

**Issue by Hirrolot** [eerimoq/nala#2]
Hello, I use Nala for my C project as I found it delightful :)

However, it is quite annoying to check what specific assertions have failed. Maybe capture line numbers inside the assertion macros and emit them if assertions have failed?

**Comment by eerimoq** [comment]
What does the output look like? I get a full backtrace with file and line numbers when an assertion fails.

**Comment by Hirrolot** [comment]
Sorry, I had to install Nala with `pip3 install nala` and type `nala init foo`, this way assertions work as expected.
