### ISSUE TITLE
Emoji is breaking pip install on Windows

### ISSUE THREAD

**Issue by dzid26** [eerimoq/nala#6]
Can you remove the emoji from `Readme.rst`?

<img width="388" alt="image" src="https://user-images.githubusercontent.com/841061/179067810-54a2ceb5-48d7-4036-a6ed-e98b8fabdb72.png">

```Processing c:\users\dzidm\downloads\nala
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dzidm\Downloads\nala\setup.py", line 17, in <module>
          long_description=open('README.rst', 'r').read(),
        File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 42: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by eerimoq** [comment]
Is probably fixed in version 0.180.0. Btw, even if nala can be installed on Windows, it will most likely not be used. It only works on linux as far as I know.

**Comment by dzid26** [comment]
Great, it worked.  It was breaking `pip install -r requirements` when I was trying cantools on Windows again . 

> Btw, even if nala can be installed on Windows, it will most likely not be used. It only works on linux as far as I know.

Maybe this is what's breaking `make test` on Windows https://github.com/cantools/cantools/issues/247.

**Comment by eerimoq** [comment]
Not sure, if it's only the slashes it can be fixed in nala. It's probably only mocking that does not work on windows, and I don't think cantools uses that. So should be possible to make it work on windows without too mush problem I think.
