### ISSUE TITLE
nala not displaying a list of packages held back, when there are packages held back.

### ISSUE THREAD

**Issue by ChrstphrR** [eerimoq/nala#7]
##Issue Summary:

No output for packages held back, when there are packages held back.

###Backgrounder:

- Using Linux kernel 5.16.3, on Ubuntu 22.04
- nala version 0.8.2
- running nala and aptitude as root using sudo

##Examples/Outputs

###Output from uname -a
Linux myhosthere 5.16.3-051603-generic #202201270732 SMP PREEMPT Thu Jan 27 12:37:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

###(Abbreviated) Output from "nala upgrade"
`root@myhosthere:/etc# nala upgrade`
`╭─ Updating Package List ─────────────────────────────────────────╮`
*snip*
`│Fetched 1566 kB in 0s (0 B/s)`
`╰─────────────────────────────────────────────────────────────────╯`
`The following packages were kept back:`
`Do you want to continue? [Y/n] `

###Output from "aptitude upgrade"

`root@myhosthere:/etc# aptitude upgrade`
`The following packages will be upgraded: `
`  fprintd isc-dhcp-client isc-dhcp-common libpam-fprintd nala`
`The following packages are RECOMMENDED but will NOT be installed:`
`  python3-socksio`
`5 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
`Need to get 495 kB of archives. After unpacking 43.0 kB will be used.`
`Do you want to continue? [Y/n/?]`

###Conclusion:
Please give further instruction if other information is required.  I hope this helps illuminate the issue I have found.

**Comment by eerimoq** [comment]
This project is a unit test framework. You are looking for another project.

**Comment by ChrstphrR** [comment]
Mea Culpa - closing - feel free to delete.
